name: compspec-go custom tag and release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Custom release tag
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set tag
        run: |
          echo "Tag for release is ${{ inputs.release_tag }}"
          echo "tag=${{ inputs.release_tag }}" >> ${GITHUB_ENV}         
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Build
        run: |
          export PATH=$PWD/bin:$PATH
          make 
          make build-arm
          make build-ppc

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: compspec-go ${{ env.tag }}
          tag_name: ${{ env.tag }}
          body: "compspec-go release ${{ env.tag }}"
          files: |
            bin/compsec
            bin/compspec-arm
            bin/compspec-ppc
        env:
          GITHUB_REPOSITORY: supercontainers/compspec-go
